name: build-llnotes

on:
  pull_request:
    types: [opened, synchronize]
    paths: ['llnotes/**']

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: llnotes/go.mod
      - name: Install Tools
        run: go install gotest.tools/gotestsum@latest
      - name: Test
        working-directory: llnotes
        run: make test

  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: llnotes/go.mod
      - name: Install Tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run make fmt
        working-directory: llnotes
        run: make fmt
      - name: Run go mod tidy
        working-directory: llnotes
        run: go mod tidy
      - name: Fail on differences
        run: |
          # Exit with status code 1 if there are differences (i.e. unformatted files)
          git diff --exit-code
